### ISSUE TITLE
An error occurred when running mol_translation_metrics.py

### ISSUE THREAD

**Issue by laituan245** [blender-nlp/MolT5#1]
I was just trying to run the example command `python mol_translation_metrics.py --input_file caption2smiles_example.txt`.

The error log
```
0 processed.
Traceback (most recent call last):
  File "C:\Users\laitu\Downloads\MolT5\evaluation\mol_translation_metrics.py", line 66, in <module>
    mscore = meteor_score([gt], out)
  File "C:\Users\laitu\Anaconda3\lib\site-packages\nltk\translate\meteor_score.py", line 397, in meteor_score
    return max(
  File "C:\Users\laitu\Anaconda3\lib\site-packages\nltk\translate\meteor_score.py", line 398, in <genexpr>
    single_meteor_score(
  File "C:\Users\laitu\Anaconda3\lib\site-packages\nltk\translate\meteor_score.py", line 326, in single_meteor_score
    enum_hypothesis, enum_reference = _generate_enums(
  File "C:\Users\laitu\Anaconda3\lib\site-packages\nltk\translate\meteor_score.py", line 33, in _generate_enums
    raise TypeError(
TypeError: "hypothesis" expects pre-tokenized hypothesis (Iterable[str]): C1=CC=C2C(=C1)C(=O)C3=C(C2=O)C=C(C=C3)C(=O)[O-]
````

**Comment by laituan245** [comment]
It is interesting that I don't see this error anymore when running on a different computer.
